name: desafio-pipeline-workflow
on:
    pull_request:
        branches:
            - develop

jobs:
    check-application:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0 
            
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm ci
            
            - name: Run tests
              run: npm test
            
            - name: Run test coverage
              run: npm run test:cov
        
            - name: Sonarcloud scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
